services:
  db:    
    image: postgres    
    restart: always    
    container_name: postgres-db
    volumes:     
      - ./init_db:/docker-entrypoint-initdb.d    
    environment:      
      POSTGRES_PASSWORD: "rootpassword"      
      POSTGRES_USER: "postgres"      
      POSTGRES_DB: "bank_accounts"
    ports:      
      - "5432:5432"    
    networks:      
      - syrax_api_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: syrax-api
    volumes:
      - .:/src
    ports:
      - "8015:8015"z
    environment:
      DECIMAL_PRECISION: "0.01"
      CORS_ALLOWED_ORIGINS: "http://localhost:80,http://localhost:8080"
      LOG_LEVEL: "10"
      POSTGRES_STRING_CONNECTION: "postgresql://postgres:rootpassword@db:5432"
      POSTGRES_DB: "bank_accounts"
    networks:
      - syrax_api_network

networks:
  syrax_api_network:
    driver: bridge